# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvl', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='FormSection4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('device_name', models.CharField(max_length=200)),
                ('indication', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='FormSection5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client_Assigned', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RC_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Project')),
            ],
        ),
        migrations.AddField(
            model_name='formsection5',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Project'),
        ),
        migrations.AddField(
            model_name='formsection4',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Project'),
        ),
        migrations.AddField(
            model_name='formsection3',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Project'),
        ),
    ]
