# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import site_ver1.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ver1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('submitter_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Project')),
            ],
        ),
        migrations.CreateModel(
            name='FormSection7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('certifier_name', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('summary_data', models.CharField(blank=True, max_length=5000, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Project')),
            ],
        ),
        migrations.CreateModel(
            name='FormSection8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_filename', models.CharField(blank=True, max_length=50, null=True)),
                ('disc_filename', models.CharField(blank=True, max_length=50, null=True)),
                ('certification', models.FileField(upload_to=site_ver1.models.get_cert_upload_filename, verbose_name='Select a file')),
                ('disclosure', models.FileField(upload_to=site_ver1.models.get_disc_upload_filename, verbose_name='Select a file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Project')),
            ],
        ),
        migrations.AddField(
            model_name='formsection5',
            name='option',
            field=models.CharField(choices=[(None, ''), ('510ksummary', '510K-Summary'), ('510kstatement', '510K-Statement')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='formsection4',
            name='device_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formsection4',
            name='indication',
            field=models.CharField(max_length=5000, verbose_name='Indications for use (Describe)'),
        ),
        migrations.AlterField(
            model_name='formsection4',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='510K Number (if known)'),
        ),
    ]
