# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_ver1', '0003_auto_20170509_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='site_ver1.Person'),
            preserve_default=False,
        ),
    ]
